### ISSUE TITLE
import module syntax changed to require

### ISSUE THREAD

**Issue by claq2** [Svakinn/TypeTowel#1]
The syntax of import lines changed in 0.9, which affects files like shell.ts. According to https://typescript.codeplex.com/wikipage?title=Known%20breaking%20changes%20between%200.8%20and%200.9

import x = module('x');

should now be

import x = require('x');

With 0.9.1 shell.ts doesn't compile.

Also, Web Essentials 2.9 removes the AMD compile option.

**Comment by Svakinn** [comment]
Thanks James for the tip. Project works fine now with TypeScript 9.0.1 and Web Essentials 2.7. I understand that next version of Web Essentials is supposed to fix this TypeScript issue with AMD
