### ISSUE TITLE
Passing paramaters from one widget to another

### ISSUE THREAD

**Issue by gyancse08** [Svakinn/TypeTowel#4]
First thanks a lot for this template! 
I was curious about how to pass paramters from one widget to anoher in typescript template. I tried some things but can not get it working. Do you have some code samples for this?

**Comment by Svakinn** [comment]
There are two ways you can go:
1. Use paramerter(s) to pass to the view
2. Use main object/class to share data between views  

First of all I suggest you take a look at the 
[SplitTowel](https://github.com/Svakinn/SplitTowel) project.  It is more advanced version of the TypeTowel.   There you see the introduction of **BaseViewmodel.ts** and **app.ts** (under the _App/base_ directory)  

The _MainClass_ in the **app.ts** is shared object that all the viewmodels that inherit the _ViewModelView_ base class have access to.  
You could add property to the _MainClass_ class, i.e. _pageMessage: string_ that you could use to pass info to a viewmodlel when you activate one view from another.  
To pass a parameter to a viewmodel (in the url) you do the following:  
a) specify a route that takes a parameter. (do this in the config.ts):

``` javascript
    public routes: Array<IRoute> = [
        { route: '', moduleId: 'home', title: 'Home', nav: 1 },
        { route: 'details', moduleId: 'details', title: 'Details', nav: 2 }
        { route: 'iteminfo/:id', moduleId: 'iteminfo', title: 'Item info', nav: 3 }
    ];  
```

Then in the lifecycle functions in the iteminfo you add this parameter.  I.e. for the activating:  

``` javascript
    public activating(parms?: any): Q.Promise<any> {
        var my = this;
        var userId = parseInt(parms);
```

To navigate to this page you can use the SplitTowel-app.ts-navigateToItem method:

``` javascript
this.app.navigateToItem('iteminfo',886):
```
